### ISSUE TITLE
Virtual COM ports above 256 not being detected in Windows

### ISSUE THREAD

**Issue by batari1** [sa666666/harmonycart#5]
I have a device that comes up in Windows as COM257, and the software would not detect it.

The problem seems to be that only com ports 1-256 are being searched. See this function: 

const StringList& SerialPortWin32::getPortNames()
{
  myPortNames.clear();

  for(int i = 1; i <= 256; ++i)
  {
    TCHAR strPort[32] = {0};
    sprintf(strPort, "COM%d", i);

    if(openPort(strPort))
    {
      uInt8 c;
      int n = receiveBlock(&c, 1);
      if(n >= 0)
        myPortNames.push_back(strPort);
    }
    closePort();
  }

In practice I have seen com ports above 1000, even back to Windows 2000. Maybe upping the limit to 1024 would help.

**Comment by sa666666** [comment]
I'll try to look into it soon.  We'll be releasing a new version of Stella soon, so that takes priority.

**Comment by sa666666** [comment]
Hopefully this fixes the issue in a better way.  We now ask Windows to enumerate the COM ports, rather than assuming the highest one is 256.

**Comment by sa666666** [comment]
I have a Windows test build for you to test the new functionality.  I've sent a message on AtariAge.  Please respond there or here, and I will provide a link.
