### ISSUE TITLE
No 64-bit versions

### ISSUE THREAD

**Issue by batari1** [sa666666/harmonycart#6]
The MacOS version of the software does not work in Catalina, since Apple went 64-bit only.

Maybe a new version of the software should be 64-bit across the board?

**Comment by sa666666** [comment]
Yep, this is now required.  Haven't tried the software in MacOS for a long time.  Guess we need to revisit this soon.

**Comment by sa666666** [comment]
This will be fixed in the next release.  Yes, I'm going with 64-bit releases only for all platforms.  Creating 32-bit versions for other platforms is too difficult, since I'd need to install multiple versions of QT Creator, etc.
