### ISSUE TITLE
Pull request

### ISSUE THREAD

**Issue by batari1** [sa666666/harmonycart#7]
The normal pull request isn't working here. The lpc21isp software used within Harmonycart has a newer version, 1.97, and relevant code changes should be brought into this project: https://sourceforge.net/projects/lpc21isp/files/lpc21isp/1.97/

Though not perfect, this version seems more reliable than older versions.

**Comment by sa666666** [comment]
I will look into it.  Please respond to my email on AtariAge about the latest test build.  I want to know if the serial port detection in Windows is now working.

**Comment by sa666666** [comment]
Redundant, fixed years ago.
