### ISSUE TITLE
CRC errors

### ISSUE THREAD

**Issue by batari1** [sa666666/harmonycart#8]
Currently, a CRC error after downloading a chunk of data halts the download. With testing, CRC errors are not repeatable and typically, if the user tries the download several times, this results in a successful download. Occasionally a board needs hits CRC errors often and the user needs to do dozens of retries to get a successful download.

The software allows changing the retry count up to 3 I believe, but I think the default retry count should be much higher than it is, at least 10, and should allow the user to select higher values still. Hopefully this would result in a much higher probability of download success.

Occasionally, after a CRC error, the software will lock up. In some instances, the only way to get the software to respond again is to unplug the board and plug it back in.

**Comment by sa666666** [comment]
Fixed in upcoming 2.0 release.
